feature/IVYPORTAL-18151-Create-Github-Action-for-Building-Documentation

diff --git a/.github/workflows/portal-documentation.yaml b/.github/workflows/portal-documentation.yaml
--- a/.github/workflows/portal-documentation.yaml
+++ b/.github/workflows/portal-documentation.yaml
@@ -60,14 +60,20 @@ jobs:
 
           MODULES=("AxonIvyPortal/portal-components" "AxonIvyPortal/portal" "AxonIvyPortal/PortalKitTestHelper" "Showcase/portal-user-examples" "Showcase/portal-developer-examples" "Showcase/InternalSupport" "Showcase/portal-components-examples")
           BUILT_MODULES=()
-          
+
+          set +e  # Allow the script to continue even if a build fails
           for MODULE in "${MODULES[@]}"; do
-            MODULE_NAME=$(basename $MODULE)
-            mvn clean install -f ${MODULE}/pom.xml
-            BUILT_MODULES+=("$MODULE")
+              if mvn clean install -f ${MODULE}/pom.xml; then
+                  BUILT_MODULES+=("$MODULE")
+              else
+                  echo "WARNING: Build failed for $MODULE" >&2
+              fi
           done
-          
-          echo "built_modules=${BUILT_MODULES[*]}" >> $GITHUB_OUTPUT
+          set -e  # Re-enable exit on error
+
+          # Debug logs
+          echo "DEBUG: BUILT_MODULES = ${BUILT_MODULES[*]}"
+          echo "built_modules=${BUILT_MODULES[*]}" | tee -a $GITHUB_OUTPUT
 
           
 
