feature/IVYPORTAL-18260-Create-GitHub-Actions-workflow-for-Selenium-test
- list all files

diff --git a/.github/workflows/portal-selenium-test.yml b/.github/workflows/portal-selenium-test.yml
--- a/.github/workflows/portal-selenium-test.yml
+++ b/.github/workflows/portal-selenium-test.yml
@@ -168,15 +168,11 @@ jobs:
             path: |
               AxonIvyPortal/portal-selenium-test/target/surefire-reports/*
         
-        - name: Archive rerun tests report
-          uses: actions/upload-artifact@v4
-          with:
-            name: rerun-test-reports
-            retention-days: 5
-            path: |
-              AxonIvyPortal/portal-selenium-test/target/surefire-reports/*.rerun
-
-
+        - name: List files in surefire-reports
+          if: always()
+          run: |
+            echo "Files in target/surefire-reports:"
+            ls -al target/surefire-reports || echo "Folder not found"
         
         - name: Report
           uses: dorny/test-reporter@v2.0.0
